[build]
builder = "dockerfile"
dockerfilePath = "../Dockerfile"
buildContext = "../"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"